{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qherde_helm.fullname" . }}
  labels:
    {{- include "qherde_helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation
data:
{{-  with .Values.configMap }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}