{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qherde_helm.fullname" . }}
  labels:
    {{- include "qherde_helm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  {{- with .Values.secret }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}